### ISSUE TITLE
Imagens 

### ISSUE THREAD

**Issue by paulovictor1997** [matheusbattisti/curso_react_yt#3]
Olá professor, me chamo Paulo Victor e estou fazendo às aulas de React pelo Youtube, só gostaria de informar que as imagens que o senhor usa no projeto, não estão disponíveis aqui no repositório. Alias às aulas são ótimas, depois de tempos tentando o React está entrando na minha cabeça.

**Comment by gcavalcantes** [comment]
Vi isso agora também. Se puder disponibilizar as imagens, agradeço.

**Comment by andrequeiroz2** [comment]
também me deparei com isso.

**Comment by luizarodrigues399** [comment]
As images estão disponiveis aqui: https://github.com/matheusbattisti/curso_react_yt/tree/16_projeto_costs/src/img
